    ProxyPreserveHost On
    RewriteEngine On
    RewriteRule ^/vast-benchmark$ /vast-benchmark/ [R=302,L]
    ProxyPass /vast-benchmark/ http://127.0.0.1:18100/
    ProxyPassReverse /vast-benchmark/ http://127.0.0.1:18100/
    <Location /vast-benchmark/>
        RequestHeader set X-Forwarded-Proto "http"
        RequestHeader set X-Forwarded-Prefix "/vast-benchmark"
    </Location>
